cargo-features = ["edition"]

[package]
name = "chess-minimax"
version = "0.1.0"
authors = ["jD91mZM2 <me@krake.one>"]
edition = "2018"

[dependencies]
# Binary dependencies
termion = { version = "1.5.1", optional = true }

[features]
bin = ["termion"]

[[bin]]
name = "main"
path = "src/main.rs"
required-features = ["bin"]
