[package]
name = "crappy-chess-minimax"
version = "0.1.0"
authors = ["LEGOlord208 <LEGOlord208@krake.one>"]

[dependencies]
cpuprofiler = { version = "0.0",  optional = true }

[dependencies.websocket]
version  = "0.20"
optional = true
default-features = false
features = ["sync"]

[features]
white  = []
public = []
cache  = []
